version: '3.8'

x-common-env: &common-env
  DATABASE_HOST: ${DATABASE_HOST}
  DATABASE_USERNAME: ${DATABASE_USERNAME}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD}

services:

  db:
    image: mysql:8
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  gateway-service:
    build: ./glampe-gateway
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"

  user-service:
    build: ./glampe-user
    ports:
      - "8081:8080"  # host:container
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DATABASE_USER: ${DATABASE_USER}
      JWT_SECRET: ${JWT_SECRET}
      REDIS_HOST: redis  # important: use service name!
      <<: *common-env

  campsite-service:
    build: ./glampe-campsite
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DATABASE_CAMPSITE: ${DATABASE_CAMPSITE}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      REDIS_HOST: redis
      <<: *common-env

  booking-service:
    build: ./glampe-booking
    ports:
      - "8083:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DATABASE_BOOKING: ${DATABASE_BOOKING}
      <<: *common-env

  payment-service:
    build: ./glampe-payment
    ports:
      - "8084:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DATABASE_PAYMENT: ${DATABASE_PAYMENT}
      <<: *common-env

  notification-service:
    build: ./glampe-notification
    ports:
      - "8085:8080"
