version: '3.8'

x-common-env: &common-env
  DATABASE_HOST: ${DATABASE_HOST}
  DATABASE_USERNAME: ${DATABASE_USERNAME}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD}

services:
  user-service:
    build: ./glampe-user
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DATABASE_USER: ${DATABASE_USER}
      <<: *common-env

  campsite-service:
    build: ./glampe-campsite
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DATABASE_CAMPSITE: ${DATABASE_CAMPSITE}
      <<: *common-env

  booking-service:
    build: ./glampe-booking
    ports:
      - "8083:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DATABASE_BOOKING: ${DATABASE_BOOKING}
      <<: *common-env

  payment-service:
    build: ./glampe-payment
    ports:
      - "8084:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DATABASE_PAYMENT: ${DATABASE_PAYMENT}
      <<: *common-env

  notification-service:
    build: ./glampe-notification
    ports:
      - "8085-8080"