server:
  port: 8085

spring:
  application:
    name: glampe-notification
  mail:
    host: smtp.gmail.com
    port: 587
    username: huatanthinh1207@gmail.com
    password: gixj iqmp fpns ylug
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest

