server:
  port: 8083

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:password}
    url: jdbc:mysql://${DATABASE_HOST:DATABASE_HOST}:3306/${DATABASE_BOOKING:DATABASE_BOOKING}

logging:
  level:
    com:
      avocado:
        client:
          campsite: DEBUG

feign:
  client:
    config:
      default:
        loggerLevel: FULL

