server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:password}
    url: jdbc:mysql://${DATABASE_HOST:host}:3306/${DATABASE_CAMPSITE:campsite}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  data:
    redis:
      port: 6379
      host: ${REDIS_HOST}
  cache:
    type: redis
  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    openfeign:
      micrometer:
        enabled: true

aws:
  accessKey: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}
  region: ap-southeast-1
  services:
    s3:
      bucket:
        name: glampe-bucket