server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:password}
    url: jdbc:mysql://${DATABASE_HOST:host}:3306/${DATABASE_USER:user}
  data:
    redis:
      port: 6379
      host: ${REDIS_HOST}
  cache:
    type: redis
  cloud:
    openfeign:
      micrometer:
        enabled: true

logging:
  level:
    org.springframework.web.socket: DEBUG
    org.springframework.messaging:  DEBUG
