


server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:password}
    url: jdbc:mysql://${DATABASE_HOST:host}:3306/${DATABASE_USER:user}
  application:
    name: user-service
  data:
    redis:
      port: 6379
      host: localhost
  cache:
    type: redis

security:
  jwt:
    secret: ${JWT_SECRET}