spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/v1/users/**
        - id: campsite-service
          uri: http://campsite-service:8082
          predicates:
            - Path=/api/v1/campsites/**
        - id: booking-service
          uri: http://booking-service:8083
          predicates:
            - Path=/api/v1/bookings/**
        - id: payment-service
          uri: http://payment-service:8084
          predicates:
            - Path=/api/v1/payments/**
        - id: notification-service
          uri: http://notification-service:8085
          predicates:
            - Path=/api/v1/notifications/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
