server:
  port: 8080

spring:
  application:
    name: glampe-api-gateway
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true

security:
  jwt:
    secret: ${JWT_SECRET}
